name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewers:
    # Replace YOUR_ORG with your actual organization name
    uses: YOUR_ORG/CI-Pipeline/.github/workflows/random-reviewer-assignment.yml@main
    with:
      # Number of reviewers to assign (default: 2)
      num_reviewers: 2
      
      # Exclude the PR author from reviewer selection (default: true)
      exclude_author: true
      
      # Enable assignment from GitHub teams (default: false)
      # Requires organization token with members:read permission
      team_reviewers: false
      
      # Path to reviewer configuration file (default: .github/reviewers.yml)
      reviewer_pool_file: '.github/reviewers.yml'
    
    secrets:
      # Option 1: Use organization token (recommended for team support)
      GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
      
      # Option 2: Use repository token (limited to individual reviewers)
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
