name: Auto Assign Reviewers (Reusable)

on:
  workflow_call:
    inputs:
      reviewers:
        description: 'JSON array of reviewer usernames'
        required: false
        type: string
        default: '["username1", "username2", "username3"]'

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest 12
    
    steps:
    - name: Auto assign reviewer
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const reviewers = JSON.parse('${{ inputs.reviewers }}');
          const prAuthor = context.payload.pull_request.user.login;
          const availableReviewers = reviewers.filter(reviewer => reviewer !== prAuthor);
          
          if (availableReviewers.length === 0) {
            console.log('No available reviewers');
            return;
          }
          
          const randomIndex = Math.floor(Math.random() * availableReviewers.length);
          const selectedReviewer = availableReviewers[randomIndex];
          
          try {
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [selectedReviewer]
            });
            
            console.log(`Successfully assigned ${selectedReviewer} as reviewer`);
          } catch (error) {
            console.error('Error assigning reviewer:', error);
          }